export enum ChatErrorCode {
  DOMAIN_PREFIX = 'D02',
  NOT_FOUND_CHAT_ROOM = '001',
  DUPLICATE_CHAT_ROOM = '002',
  FAILED_TO_CREATE_CHAT_ROOM = '003',
  FAILED_TO_DELETE_CHAT_ROOM = '004',
  FAILED_TO_UPDATE_CHAT_ROOM = '005',
  FAILED_TO_GET_CHAT_ROOM = '006',
  FAILED_TO_ADD_MESSAGE_TO_CHAT_ROOM = '007',
  FAILED_TO_DELETE_MESSAGE_FROM_CHAT_ROOM = '008',
  FAILED_TO_ADD_USER_TO_CHAT_ROOM = '009',
  FAILED_TO_DELETE_USER_FROM_CHAT_ROOM = '010',
}
