export enum UserErrorCode {
  DOMAIN_PREFIX = 'D01',
  DUPLICATE_EMAIL = '001',
  NOT_FOUND_USER = '003',
  FAILED_TO_CREATE_USER = '004',
  FAILED_TO_DELETE_USER = '005',
  FAILED_TO_UPDATE_USER = '006',
}
